services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 3000
    stop_grace_period: 2m
